services:
  postgres-source:
    image: postgis/postgis:13-3.3
    platform: linux/amd64
    container_name: postgres-source
    environment:
      - POSTGRES_DB=ride_hailing_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - postgres_source_data:/var/lib/postgresql/data
    networks: [ streaming_network ]

  postgres-reporting:
    image: postgres:13
    platform: linux/amd64
    container_name: postgres-reporting
    environment:
      - POSTGRES_DB=reporting_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init-reporting-db.sql:/docker-entrypoint-initdb.d/01-init-reporting-db.sql
      - postgres_reporting_data:/var/lib/postgresql/data
    networks: [ streaming_network ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    platform: linux/amd64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: [ "2181:2181" ]
    networks: [ streaming_network ]

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    platform: linux/amd64
    container_name: kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: [ streaming_network ]

  kafka-connect:
    image: quay.io/debezium/connect:2.6
    platform: linux/amd64
    container_name: kafka-connect
    depends_on: [ kafka ]
    ports: [ "8083:8083" ]
    environment:
      BOOTSTRAP_SERVERS: kafka:19092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    networks: [ streaming_network ]
    volumes:
      - ./connectors:/kafka/connectors

  flink-jobmanager:
    image: flink:1.17.2-java11
    platform: linux/amd64
    container_name: flink-jobmanager
    depends_on: [ kafka ]
    ports: [ "8081:8081" ]
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./flink-job/target:/jars
      #- ./flink_libs:/opt/flink/lib
    networks: [ streaming_network ]

  flink-taskmanager:
    image: flink:1.17.2-java11
    platform: linux/amd64
    container_name: flink-taskmanager
    depends_on: [ flink-jobmanager ]
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks: [ streaming_network ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    platform: linux/amd64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: [ "9200:9200" ]
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks: [ streaming_network ]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    platform: linux/amd64
    container_name: kibana
    depends_on: [ elasticsearch ]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: [ "5601:5601" ]
    networks: [ streaming_network ]

  superset:
    image: apache/superset:3.0.0
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=thisISaSECRET_1234567890
      - SUPERSET_LOAD_EXAMPLES=no
      - TALISMAN_ENABLED=False
    ports:
      - "8088:8088"
    depends_on:
      - postgres-reporting
    networks:
      - streaming_network
    volumes:
      - superset_home:/app/superset_home
      - ./superset/database_config.yaml:/app/superset_home/database_config.yaml:ro
      - ./superset/bootstrap.sh:/app/superset_home/bootstrap.sh:ro
    command: ["/bin/bash", "/app/superset_home/bootstrap.sh"]

networks:
  streaming_network:
    driver: bridge

volumes:
  postgres_source_data:
  postgres_reporting_data:
  elasticsearch_data:
  superset_home:
